#!/bin/sh
# SPDX-License-Identifier: GPL-2.0+
seq=`basename $0`
seqres=$RESULT_DIR/$seq

# get standard environment, filters and checks
. "${srcdir}/common/rc"

cleanup()
{
	cd /
	rm -rf $tmp.*
}

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here
echo "QA output created by $seq"

if [ -z $SCRATCH_DEV ]; then
	SCRATCH_DEV=$tmp/erofs_$seq.img
	rm -f SCRATCH_DEV
fi

localdir="$tmp/$seq"
rm -rf $localdir
mkdir -p $localdir

# create pipe
mknod $localdir/pipefile p

_scratch_mkfs $localdir || _fail "failed to mkfs"

# test pipe files
_require_erofs

_scratch_mount 2>>$seqres.full

ttypefifo='fifo:0,0'

[ "x$(stat -c "%F:%t,%T" $SCRATCH_MNT/pipefile | tr -d '\n')" = "x$ttypefifo" ] || \
       _fail "-->checkpipe FAILED"

_scratch_unmount

echo Silence is golden
status=0
exit 0
