#!/bin/sh
# SPDX-License-Identifier: GPL-2.0+
seq=`basename $0`
seqres=$RESULT_DIR/$seq

# get standard environment, filters and checks
. "${srcdir}/common/rc"

cleanup()
{
	cd /
	rm -rf $tmp.*
}

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here
echo "QA output created by $seq"

if [ -z $SCRATCH_DEV ]; then
	SCRATCH_DEV=$tmp/erofs_$seq.img
	rm -f SCRATCH_DEV
fi

localdir="$tmp/$seq"
rm -rf $localdir

[ "$(id -u)" = "0" ] || \
	_notrun "This testcase must be run as root, skipped."

mkdir -p $localdir/d1
mkdir -p $localdir/d2/d3/d4 $localdir/d2/d5
touch $localdir/d1/a
ln $localdir/d1/a $localdir/d2/a
ln $localdir/d1/a $localdir/d2/d3/a

_scratch_mkfs $localdir || _fail "failed to mkfs"

# check i_nlink count is expected
_require_erofs

_scratch_mount 2>>$seqres.full

[ `stat -c %h $SCRATCH_MNT` -eq 4 -a \
  `stat -c %h $SCRATCH_MNT/d1` -eq 2 -a \
  `stat -c %h $SCRATCH_MNT/d2` -eq 4 -a \
  `stat -c %h $SCRATCH_MNT/d2/d3` -eq 3 -a \
  `stat -c %h $SCRATCH_MNT/d1/a` -eq 3 ] || \
	_fail "-> check i_nlink FAILED"

_scratch_unmount

echo Silence is golden
status=0
exit 0
